homeassistant:
  auth_providers:
   - type: homeassistant
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables configuration UI
frontend: 
  javascript_version: latest
  themes: !include_dir_merge_named themes

config:

hassio:

api:

#http:

updater:

conversation:

history: !include history.yaml

recorder: !include recorder.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js
      type: module
    - url: /hacsfiles/custom-header/custom-header.js
      type: module
    - url: /hacsfiles/bar-card/bar-card.js
      type: module
    - url: /hacsfiles/lovelace-card-tools/card-tools.js
      type: module
    - url: /hacsfiles/lovelace-popup-card/popup-card.js
      type: js
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
      type: module
    - url: /hacsfiles/old-vertical-stack-in-card/vertical-stack-in-card.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/weather-card/weather-card.js
      type: module
    - url: /hacsfiles/lovelace-state-switch/state-switch.js
      type: module
    - url: /hacsfiles/lovelace-time-picker-card/time-picker-card.js
      type: module
    - url: /hacsfiles/vacuum-card/vacuum-card.js
      type: module

    - url: /local/hui-view-settings.js
      type: js
    - url: /local/popup-background.js
      type: js
      
    
    - url: 'https://fonts.googleapis.com/css?family=Raleway'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Oswald'
      type: css
    - url: 'https://fonts.googleapis.com/css?family=Quicksand'
      type: css

system_health:

#logbook:

sun:

ssdp:

zeroconf:

person:

mobile_app:

logger:
  default: critical

## HOME ASSISTANT CLOUD #################################################################
cloud:

## TTS ##################################################################################
tts:
  - platform: google_translate
    language: 'de'

## MEDIA PLAYER #########################################################################
# media_player:
#   - platform: androidtv
#     name: FireTV - Wohnzimmer
#     host: 192.168.0.78
#     apps:
#       com.amazon.tv.launcher: "Fire TV"
#       com.netflix.ninja: "Netflix"
#       com.amazon.avod: "Amazon Video"
#       com.amazon.firetv.youtube: "YouTube"
#     state_detection_rules:
#       'com.amazon.tv.launcher':
#         - 'standby'
#       'com.netflix.ninja':
#         - 'media_session_state'
#       'com.amazon.avod':
#         - 'media_session_state'
  
## HUE ##################################################################################
hue:
  bridges:
    - host: 10.0.0.10
      allow_hue_groups: true
      allow_unreachable: true

## DEVICE TRACKERS ######################################################################
device_tracker:
  - platform: fritz
    host: 10.0.0.1
    track_new_devices: True
    consider_home: 90
  - platform: mqtt_json
    devices:
      niu: home/niu/position

## WEATHER ##############################################################################
weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key
    mode: freedaily

## UTILITY METER ########################################################################
utility_meter:
  niu_watts_monthly:
    source: sensor.hs110_today_energy_kwh
    cycle: monthly
  niu_watts_yearly:
    source: sensor.hs110_today_energy_kwh
    cycle: yearly
  net_received_monthly:
    source: sensor.net_received
    cycle: monthly
  net_sent_monthly:
    source: sensor.net_sent
    cycle: monthly

## PING #################################################################################
binary_sensor:
  - platform: ping
    host: 10.0.0.2
    count: 1
    scan_interval: 10
    name: Pi-Hole

lovelace_gen:

pi_hole:
  - host: 10.0.0.2:80
    api_key: !secret pi_hole_api_key

shell_command:
  reboot_pi: "ssh -i /config/ssh/id_rsa -o StrictHostKeyChecking=no pi@10.0.0.2 'sudo reboot'"

vacuum:
  - platform: xiaomi_miio
    host: 10.0.0.16
    token: 73374466445051533764425965534c74

# alexa_media:
#   accounts:
#     - email: !secret amazon_user
#       password: !secret amazon_password
#       url: amazon.com

input_boolean: !include_dir_merge_named input_boolean
input_select: !include_dir_merge_named input_select
input_number: !include_dir_merge_named input_number
scene: !include scenes.yaml
script: !include_dir_merge_named scripts
sensor: !include_dir_merge_list sensor
