- platform: template
  sensors:
    andre_mi9t_battery_charging:
      value_template: >
        {%- if is_state_attr('sensor.andre_mi9t_battery_level','is_charging',true) %}on
        {%- elif is_state_attr('sensor.andre_mi9t_battery_level','is_charging',false) %}Off
        {% else %}unknown{%- endif %}
      friendly_name: "Handy - Andre Laden"
      icon_template: >
        {%- if is_state_attr('sensor.andre_mi9t_battery_level','is_charging',true) %}mdi:flash
        {%- elif is_state_attr('sensor.andre_mi9t_battery_level','is_charging',false) %}mdi:blank
        {% else %}mdi:alert-circle-outline{%- endif %}

