- platform: template
  sensors:
    proximity_traveldir_julienne:
      value_template: "{{ state_attr('proximity.home_julienne', 'dir_of_travel') }}"
      friendly_name: "Fahrtrichtung"
      icon_template: >
        {% if is_state_attr('proximity.home_julienne', 'dir_of_travel', 'towards') %}
          mdi:arrow-down-bold
        {% elif is_state_attr('proximity.home_julienne', 'dir_of_travel', 'away_from') %}
          mdi:arrow-up-bold
        {% elif is_state_attr('proximity.home_julienne', 'dir_of_travel', 'stationary') %}
          mdi:arrow-all
        {% else %}
          mdi:map-marker-question
        {% endif %}

- platform: template
  sensors:
    proximity_traveldir_andre:
      value_template: "{{ state_attr('proximity.home_andre', 'dir_of_travel') }}"
      friendly_name: "Fahrtrichtung"
      icon_template: >
        {% if is_state_attr('proximity.home_andre', 'dir_of_travel', 'towards') %}
          mdi:arrow-down-bold
        {% elif is_state_attr('proximity.home_andre', 'dir_of_travel', 'away_from') %}
          mdi:arrow-up-bold
        {% elif is_state_attr('proximity.home_andre', 'dir_of_travel', 'stationary') %}
          mdi:arrow-all
        {% else %}
          mdi:map-marker-question
        {% endif %}