#########
# GROUP #
#########
group:
  all_persons:
    name: Personen
    entities:
      - person.andre
      - person.julienne

################
# INPUT_SELECT #
################
input_select:

  presence_andre:
    options:
      - Zu Hause
      - Angekommen
      - Verlassen
      - Abwesend
      - Lange Abwesend
      - Arbeit
      - Anne & Fred
      - Nicole & Marc
      - Papito

  presence_julienne:
    options:
      - Zu Hause
      - Angekommen
      - Verlassen
      - Abwesend
      - Extended Away
      - Arbeit
      - Anne & Fred
      - Nicole & Marc
      - Papito

##########
# SENSOR #
##########
sensor:
  - platform: template
    sensors:
      andre_status:
        value_template: '{{ states.input_select.presence_andre.state }}'
        friendly_name: 'Andre'
      julienne_status:
        value_template: '{{ states.input_select.presence_julienne.state }}'
        friendly_name: 'Julienne'